### ISSUE TITLE
C-CAP project layers, csv files

### ISSUE THREAD

**Issue by kflahertywalia** [tbep-tech/c-cap#1]
All are located here: https://drive.google.com/drive/u/0/folders/1dZDITj0NlUZWC_aZY61v9R5L2yU8IQ15

Some of these files are rather large and probably not appropriate to add to github. Is there anywhere else that we should store these, or just add/revise R code to recreate and link to the google drive?

**Comment by fawda123** [comment]
@kflahertywalia I rewordked `R/CCAP.R` to pull in the CSV files from Google Drive since they're too big to include here.  The shapefiles aren't used anywhere in the R file, so nothing to do there other than provide a link in the readme.  It's probably good to ask Kara to change the permissions to read only, except for us.
